Baven
=====
Nathaniel Harward <nharward@gmail.com>


What is Baven exactly?
----------------------
Baven is intended to offer BASH code reuse through a Maven-like plugin
facility.  Say you're writing a BASH script and you decide you want some nice
color/highlighted output, but only when the user is on a terminal otherwise
you want plain text.  You can:

* Figure out ascii codes and cook them into your script
* Search the web and see if someone has already done it
* Include +baven.bash+ into your program, then load the +ansi-color+ plugin
  and have BASH functions available to you for free

I opt for the last option, now I never have to write that again if I want
colorized output in a script.


How does it work?
-----------------
Just like anything else, you have to somehow bootstrap the system to use it.
For Baven this means having +baven.bash+ in your PATH, it can be found in the
distribution under +bin/+.  Then you load the plugin(s) you want and their
functions and variables are sourced into your BASH environment for your use.
Please see the +bin/samples/+ directory for scripts that use Baven to
demonstrate some of the plugins.


What dependencies does it have?
-------------------------------
While very powerful, BASH is not quite as rich as say Java, C++, Ruby...  In
order to work with networked repositories, do checksumming, etc. some other
programs are used that are not packaged (nor should be) with Baven.  Here are
some of the major dependencies, though on most Linux systems this shouldn't be
an issue:
* +md5sum+
* +sha1sum+
* One of the following, they are checked for in this order:
** +curl+
** +wget+
** +w3m+
** +links+
** +elinks+
** +lynx+

There are other more basic dependencies such as +mkdir+, +test+, +rm+...
But there aren't many and if those are missing I'm not sure how any real
script would work anyway.


Maven has network-aware repositories, does Baven?
-------------------------------------------------
Yes, Baven has support for any number of repositories, as long as their
definition can fit inside a BASH array.  When first sourced, Baven will create a
configuration file and repository location in +$\{HOME}/.baven+.  You can
add/remove repositories to your liking once this is done.

Note that Baven repositories are modeled after Maven repositories.  Also, both
MD5 and SHA1 checksums must match otherwise the plugin will not be loaded and
the next repository will be checked.

Repositories are accessed using other tools like curl, wget, lynx, etc.  Curl is
first on the list, so whatever URL schemes are supported by the tool in use on
your system is available to you.  Curl on my system supports +file://+, so my
first entry in +$\{HOME}/.baven/baven-conf.bash+ points to my Git checkout so I
avoid a network hop and can easily test plugins I'm writing.


I don't like the default repository, I want my own
--------------------------------------------------
Go nuts.  All you need is a place to host files that is accessible by
curl/lynx/etc.  I would recommend using git to check out this repository
and pull once in a while, and push your personal/corporate/local plugins to
your own repo.  Maven needs separate handling to manage repositories nicely
but by using git you get it nearly for free.  That's actually the reason I
chose Github to host the project.


TODO
----
Lots more to do including making a plugin to help package/deploy new plugins
among others.
